--------------------------------------------------------------------------------
-- Banner AR Interactive Help POC - Schema
-- Target: Oracle
--
-- Notes on changes vs. the original technical design doc:
--   - poc_ar_detail_code: added GRANT_TYPE_CODE, REFUNDABLE_IND, RECEIPT_IND,
--     TERM_BASED_IND, AID_YEAR_BASED_IND. These were referenced in the doc's
--     field mapping (section 3.2) and seed INSERTs (section 10) but were
--     missing from its own CREATE TABLE statement.
--   - poc_term: added AID_YEAR_CODE (referenced in seed data, missing from DDL).
--   - poc_person: added HOLD_IND, needed for the TSADETL rule "Account has an
--     AR hold; transaction entry is not permitted" (section 7.3).
--   - poc_ar_transaction: added STATUS_CODE (the doc's own balance queries
--     filter on t.status_code = 'A' but the column never existed), plus
--     AID_YEAR_CODE and ORIGINAL_CHARGE_IND from the field mapping table.
--   - poc_ar_account_summary: no DDL existed in the doc at all; added here
--     since it's listed as one of the 7 core POC tables.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. POC_AR_CATEGORY  (simulates TTVDCAT)
--------------------------------------------------------------------------------
CREATE TABLE poc_ar_category (
    category_code          VARCHAR2(4 CHAR)  NOT NULL,
    description            VARCHAR2(60 CHAR) NOT NULL,
    system_required_ind    CHAR(1) DEFAULT 'N' NOT NULL,
    active_ind             CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by             VARCHAR2(30 CHAR) DEFAULT USER NOT NULL,
    updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by             VARCHAR2(30 CHAR) DEFAULT USER NOT NULL,
    CONSTRAINT pk_poc_ar_category PRIMARY KEY (category_code),
    CONSTRAINT ck_poc_ar_cat_code_upper CHECK (category_code = UPPER(category_code)),
    CONSTRAINT ck_poc_ar_cat_sys CHECK (system_required_ind IN ('Y','N')),
    CONSTRAINT ck_poc_ar_cat_active CHECK (active_ind IN ('Y','N'))
);

--------------------------------------------------------------------------------
-- 2. POC_AR_DETAIL_CODE  (simulates TSADETC)
--------------------------------------------------------------------------------
CREATE TABLE poc_ar_detail_code (
    detail_code            VARCHAR2(4 CHAR)  NOT NULL,
    description            VARCHAR2(60 CHAR) NOT NULL,
    type_code              CHAR(1)           NOT NULL,   -- C = charge, P = payment
    category_code          VARCHAR2(4 CHAR)  NOT NULL,
    grant_type_code        VARCHAR2(4 CHAR),
    priority_no            NUMBER(3) DEFAULT 0 NOT NULL,
    term_based_ind         CHAR(1) DEFAULT 'Y' NOT NULL,
    aid_year_based_ind     CHAR(1) DEFAULT 'N' NOT NULL,
    refundable_ind         CHAR(1) DEFAULT 'N' NOT NULL,
    receipt_ind            CHAR(1) DEFAULT 'N' NOT NULL,
    active_ind             CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by             VARCHAR2(30 CHAR) DEFAULT USER NOT NULL,
    updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by             VARCHAR2(30 CHAR) DEFAULT USER NOT NULL,
    CONSTRAINT pk_poc_ar_detail_code PRIMARY KEY (detail_code),
    CONSTRAINT fk_poc_ar_det_category FOREIGN KEY (category_code)
        REFERENCES poc_ar_category (category_code),
    CONSTRAINT ck_poc_ar_det_type CHECK (type_code IN ('C','P')),
    CONSTRAINT ck_poc_ar_det_priority CHECK (priority_no BETWEEN 0 AND 999),
    CONSTRAINT ck_poc_ar_det_term_based CHECK (term_based_ind IN ('Y','N')),
    CONSTRAINT ck_poc_ar_det_aid_year CHECK (aid_year_based_ind IN ('Y','N')),
    CONSTRAINT ck_poc_ar_det_refundable CHECK (refundable_ind IN ('Y','N')),
    CONSTRAINT ck_poc_ar_det_receipt CHECK (receipt_ind IN ('Y','N')),
    CONSTRAINT ck_poc_ar_det_active CHECK (active_ind IN ('Y','N')),
    -- "Term/Aid Year Based - both cannot be Y in this reduced POC" (doc section 7.2)
    CONSTRAINT ck_poc_ar_det_period_type CHECK (
        NOT (term_based_ind = 'Y' AND aid_year_based_ind = 'Y')
    )
);

CREATE INDEX ix_poc_ar_det_category ON poc_ar_detail_code (category_code);

--------------------------------------------------------------------------------
-- 3. POC_PERSON  (synthetic student/account identity)
--------------------------------------------------------------------------------
CREATE TABLE poc_person (
    person_key             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    banner_id              VARCHAR2(9 CHAR) NOT NULL,
    display_name           VARCHAR2(120 CHAR) NOT NULL,
    active_ind             CHAR(1) DEFAULT 'Y' NOT NULL,
    hold_ind                CHAR(1) DEFAULT 'N' NOT NULL,   -- AR hold, blocks new transactions on TSADETL
    credit_limit           NUMBER(12,2),
    CONSTRAINT pk_poc_person PRIMARY KEY (person_key),
    CONSTRAINT uk_poc_person_banner_id UNIQUE (banner_id),
    CONSTRAINT ck_poc_person_active CHECK (active_ind IN ('Y','N')),
    CONSTRAINT ck_poc_person_hold CHECK (hold_ind IN ('Y','N'))
);

--------------------------------------------------------------------------------
-- 4. POC_TERM  (simulates STVTERM)
--------------------------------------------------------------------------------
CREATE TABLE poc_term (
    term_code              VARCHAR2(6 CHAR) NOT NULL,
    description            VARCHAR2(60 CHAR) NOT NULL,
    aid_year_code          VARCHAR2(4 CHAR),
    start_date             DATE,
    end_date               DATE,
    active_ind             CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_poc_term PRIMARY KEY (term_code),
    CONSTRAINT ck_poc_term_active CHECK (active_ind IN ('Y','N')),
    CONSTRAINT ck_poc_term_dates CHECK (
        start_date IS NULL OR end_date IS NULL OR start_date <= end_date
    )
);

--------------------------------------------------------------------------------
-- 5. POC_AR_TRANSACTION  (simulates TSADETL account-detail activity)
--------------------------------------------------------------------------------
CREATE TABLE poc_ar_transaction (
    transaction_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    person_key             NUMBER NOT NULL,
    transaction_no         NUMBER(9) NOT NULL,
    detail_code            VARCHAR2(4 CHAR) NOT NULL,
    term_code              VARCHAR2(6 CHAR) NOT NULL,
    aid_year_code          VARCHAR2(4 CHAR),
    entry_amount           NUMBER(12,2) NOT NULL,
    signed_amount          NUMBER(12,2) NOT NULL,
    open_balance           NUMBER(12,2) NOT NULL,
    original_charge_ind    CHAR(1) DEFAULT 'N' NOT NULL,
    status_code            CHAR(1) DEFAULT 'A' NOT NULL,   -- A = active, V = voided
    transaction_date       DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by             VARCHAR2(30 CHAR) DEFAULT USER NOT NULL,
    CONSTRAINT pk_poc_ar_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT uk_poc_ar_tran_no UNIQUE (person_key, transaction_no),
    CONSTRAINT fk_poc_ar_tran_person FOREIGN KEY (person_key)
        REFERENCES poc_person (person_key),
    CONSTRAINT fk_poc_ar_tran_detail FOREIGN KEY (detail_code)
        REFERENCES poc_ar_detail_code (detail_code),
    CONSTRAINT fk_poc_ar_tran_term FOREIGN KEY (term_code)
        REFERENCES poc_term (term_code),
    CONSTRAINT ck_poc_ar_tran_entry_amt CHECK (entry_amount > 0),
    CONSTRAINT ck_poc_ar_tran_original CHECK (original_charge_ind IN ('Y','N')),
    CONSTRAINT ck_poc_ar_tran_status CHECK (status_code IN ('A','V'))
);

CREATE INDEX ix_poc_ar_tran_person_term ON poc_ar_transaction (person_key, term_code);
CREATE INDEX ix_poc_ar_tran_detail      ON poc_ar_transaction (detail_code);
CREATE INDEX ix_poc_ar_tran_status      ON poc_ar_transaction (status_code);

--------------------------------------------------------------------------------
-- 6. POC_AR_ACCOUNT_SUMMARY  (optional cached/demo balance region on TSADETL)
--------------------------------------------------------------------------------
CREATE TABLE poc_ar_account_summary (
    person_key             NUMBER NOT NULL,
    term_code              VARCHAR2(6 CHAR) NOT NULL,
    account_balance        NUMBER(12,2) DEFAULT 0 NOT NULL,
    refreshed_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_poc_ar_acct_summary PRIMARY KEY (person_key, term_code),
    CONSTRAINT fk_poc_ar_acct_person FOREIGN KEY (person_key)
        REFERENCES poc_person (person_key),
    CONSTRAINT fk_poc_ar_acct_term FOREIGN KEY (term_code)
        REFERENCES poc_term (term_code)
);

--------------------------------------------------------------------------------
-- 7. POC_HELP_METADATA  (RAG/help facts and page-field lineage)
--------------------------------------------------------------------------------
CREATE TABLE poc_help_metadata (
    help_id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    page_code              VARCHAR2(8 CHAR) NOT NULL,
    field_name             VARCHAR2(60 CHAR),
    topic                  VARCHAR2(100 CHAR) NOT NULL,
    help_text              CLOB NOT NULL,
    source_page_code       VARCHAR2(8 CHAR),
    source_object_name     VARCHAR2(30 CHAR),
    target_page_code       VARCHAR2(8 CHAR),
    target_object_name     VARCHAR2(30 CHAR),
    active_ind             CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_poc_help_metadata PRIMARY KEY (help_id),
    CONSTRAINT ck_poc_help_active CHECK (active_ind IN ('Y','N'))
);

CREATE INDEX ix_poc_help_page_field ON poc_help_metadata (page_code, field_name);
